version: '3'
services:
  db:
    image: mysql/mysql-server:5.7
    restart: always
    ports:
      - 3306:3306
    env_file:
      - db.env
    volumes:
      - /data:/var/lib/mysql
      - ./mysql_config/my.cnf:/etc/my.cnf
      - ./sql-script:/docker-entrypoint-initdb.d
  api-flask:
     build: .
     command: ["/app/wait-for-it.sh","db:3306","--","bash","-c","flask run --host=0.0.0.0"]
     ports:
       - 5000:5000
     depends_on:
       - db
